name: .NET CICD Pipeline 

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build dependencies
        run: dotnet build --configuration Release

      - name: Run Tests (if any)
        run: dotnet test --configuration release
        
